name: 'PR Author Check'
description: 'Check if PR author belongs to organization or not'
inputs:
  org: # id of input
    description: 'Organization name'
    required: true
  token:
    description: 'GitHub token'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
