on: [pull_request]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    name: A job to label community PRs
    steps:
      - name: Check event payload
        uses: debdutdeb/action@main
        with:
          org: 'RocketChat'
